import type { Session } from "@supabase/supabase-js";
import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from "react";
import { supabase } from "@/integrations/supabase/client";

export type Onboarding = { ageRange:string; experience:string; location:string; equipment:string[]; daysPerWeek:string; workoutTime:string; goals:string[]; sleepSchedule:string; activityLevel:string; workSchedule:string; timePerDay:string; diet:string; place:string; level:string; duration:string };
export type VeyraUser = { name:string; email:string; role:"user"|"admin"; plan:"free"|"starter"|"pro"|"elite"; joinedAt:string };
export type WorkoutSession = { id:string; date:string; title:string; feedback:"easy"|"good"|"challenging"|"too_difficult"|null };
export type HabitDefinition = { id:string; name:string; custom?:boolean };
export type ChatMessage = { id:string; role:"user"|"coach"; content:string };
export type VeyraState = { user:VeyraUser|null; onboarding:Onboarding|null; habits:HabitDefinition[]; completions:Record<string,string[]>; sessions:WorkoutSession[]; completedExercises:string[]; messages:ChatMessage[]; theme:"dark"|"light"; notifications:{workout:boolean;habits:boolean;weekly:boolean}; privacy:{analytics:boolean;personalization:boolean}; totalXp:number; currentLevel:number; currentRank:string; currentStreak:number; longestStreak:number };
export const DEFAULT_HABITS:HabitDefinition[]=[{id:"workout",name:"Workout"},{id:"sleep",name:"Sleep routine"},{id:"hydration",name:"Hydration"},{id:"grooming",name:"Personal grooming"},{id:"movement",name:"Movement"},{id:"focus",name:"Study/work focus"}];
const STORAGE_KEY="veyra-state-v3";
const initialState:VeyraState={user:null,onboarding:null,habits:DEFAULT_HABITS,completions:{},sessions:[],completedExercises:[],messages:[],theme:"dark",notifications:{workout:true,habits:true,weekly:true},privacy:{analytics:true,personalization:true},totalXp:0,currentLevel:1,currentRank:"Bronze",currentStreak:0,longestStreak:0};
export type AuthResult={error:string|null;needsEmailConfirmation?:boolean};
export type XpResult={levelUp:boolean;level:number;totalXp:number;awarded:boolean};
type Ctx={state:VeyraState;hydrated:boolean;authLoading:boolean;update:(patch:Partial<VeyraState>)=>void;signUpWithPassword:(name:string,email:string,password:string)=>Promise<AuthResult>;signInWithPassword:(email:string,password:string)=>Promise<AuthResult>;signInWithGoogle:()=>Promise<AuthResult>;signOut:()=>Promise<void>;awardXp:(amount:number,source:string,sourceKey:string)=>Promise<XpResult|null>;toggleHabit:(id:string,date?:string)=>void;addHabit:(name:string)=>void;removeHabit:(id:string)=>void;completeWorkout:(title:string,feedback:WorkoutSession["feedback"])=>void;toggleExercise:(id:string)=>void};
const VeyraContext=createContext<Ctx|null>(null);
export const todayKey=()=>new Date().toISOString().slice(0,10);
export const dayKey=(offset:number)=>{const d=new Date();d.setDate(d.getDate()-offset);return d.toISOString().slice(0,10)};
export function xpForLevel(level:number){return 25*level**2}
export function levelFromXp(xp:number){let level=1;while(xp>=xpForLevel(level)&&level<100)level+=1;return level}
export function rankFromLevel(level:number){if(level>=31)return "Platinum";if(level>=11)return "Gold";return "Bronze"}
function streaks(completions:Record<string,string[]>){let current=0;for(let i=0;i<365;i++){if(!(completions[dayKey(i)]??[]).length)break;current++}let longest=0,run=0;for(let i=364;i>=0;i--){if((completions[dayKey(i)]??[]).length){run++;longest=Math.max(longest,run)}else run=0}return{current,longest}}
function withProgress(state:VeyraState,totalXp:number,completions=state.completions):VeyraState{const level=levelFromXp(Math.max(0,totalXp));const s=streaks(completions);return{...state,totalXp:Math.max(0,totalXp),currentLevel:level,currentRank:rankFromLevel(level),currentStreak:s.current,longestStreak:Math.max(state.longestStreak,s.longest)}}
function authError(error:unknown){if(error&&typeof error==="object"&&"message"in error)return String((error as {message:unknown}).message);return "Something went wrong. Please try again."}
async function loadProfile(session:Session){const email=session.user.email??"";const meta=session.user.user_metadata??{};const fallbackName=String(meta["display_name"]??meta["full_name"]??email.split("@")[0]??"Friend");const {data}=await supabase.from("profiles").select("display_name,email,plan,onboarding,created_at").eq("id",session.user.id).maybeSingle();return{user:{name:data?.display_name||fallbackName,email:data?.email||email,role:email.toLowerCase().startsWith("admin")?"admin":"user",plan:(data?.plan as VeyraUser["plan"])||"free",joinedAt:data?.created_at||session.user.created_at||new Date().toISOString()},onboarding:(data?.onboarding as Onboarding|null)??null}}
async function loadRemoteState(userId:string){const [p,h,c,w]=await Promise.all([supabase.from("user_progress").select("total_xp,level,rank,current_streak,longest_streak").eq("user_id",userId).maybeSingle(),supabase.from("habits").select("id,key,name,is_custom,sort_order").eq("user_id",userId).order("sort_order"),supabase.from("habit_completions").select("habit_id,completed_on,habits!inner(key)").eq("user_id",userId).order("completed_on",{ascending:false}).limit(1000),supabase.from("workout_sessions").select("id,performed_on,title,feedback").eq("user_id",userId).order("performed_on",{ascending:false}).limit(100)]);const habits:HabitDefinition[]=h.data?.length?h.data.map(x=>({id:x.key,name:x.name,custom:x.is_custom})):DEFAULT_HABITS;const completions:Record<string,string[]>={};for(const row of c.data??[]){const rel=Array.isArray(row.habits)?row.habits[0]:row.habits;if(rel?.key)completions[row.completed_on]=[...(completions[row.completed_on]??[]),rel.key]}const sessions=(w.data??[]).map(x=>({id:x.id,date:x.performed_on,title:x.title,feedback:(x.feedback as WorkoutSession["feedback"])??null}));return{totalXp:p.data?.total_xp??0,currentLevel:p.data?.level??1,currentRank:p.data?.rank?p.data.rank.charAt(0).toUpperCase()+p.data.rank.slice(1):"Bronze",currentStreak:p.data?.current_streak??0,longestStreak:p.data?.longest_streak??0,habits,completions,sessions}}

export function VeyraProvider({children}:{children:ReactNode}){
 const[state,setState]=useState(initialState);const[hydrated,setHydrated]=useState(false);const[authLoading,setAuthLoading]=useState(true);
 useEffect(()=>{try{const raw=localStorage.getItem(STORAGE_KEY);if(raw)setState(p=>({...p,...JSON.parse(raw)}))}catch{}setHydrated(true)},[]);
 useEffect(()=>{if(!hydrated)return;localStorage.setItem(STORAGE_KEY,JSON.stringify({theme:state.theme,notifications:state.notifications,privacy:state.privacy,completedExercises:state.completedExercises,messages:state.messages}))},[hydrated,state.theme,state.notifications,state.privacy,state.completedExercises,state.messages]);
 useEffect(()=>{if(hydrated)document.documentElement.classList.toggle("dark",state.theme==="dark")},[hydrated,state.theme]);
 const hydrateSession=useCallback(async(session:Session)=>{try{const[{user,onboarding},remote]=await Promise.all([loadProfile(session),loadRemoteState(session.user.id)]);setState(p=>withProgress({...p,user,onboarding,...remote},remote.totalXp,remote.completions))}catch{setState(p=>({...p,user:{name:String(session.user.user_metadata?.["display_name"]??session.user.email?.split("@")[0]??"Friend"),email:session.user.email??"",role:"user",plan:"free",joinedAt:session.user.created_at},onboarding:p.onboarding}))}},[]);
 useEffect(()=>{let cancelled=false;const init=async()=>{try{const{data}=await supabase.auth.getSession();if(cancelled)return;if(data.session)await hydrateSession(data.session)}finally{if(!cancelled)setAuthLoading(false)}};void init();const{data:{subscription}}=supabase.auth.onAuthStateChange((event,session)=>{if(cancelled)return;if(event==="SIGNED_OUT"||!session){setState(p=>({...initialState,theme:p.theme,notifications:p.notifications,privacy:p.privacy}));setAuthLoading(false)}else{setAuthLoading(true);void hydrateSession(session).finally(()=>{if(!cancelled)setAuthLoading(false)})}});return()=>{cancelled=true;subscription.unsubscribe()}},[hydrateSession]);
 const update=useCallback((patch:Partial<VeyraState>)=>setState(p=>({...p,...patch})),[]);
 const signUpWithPassword=useCallback(async(name:string,email:string,password:string):Promise<AuthResult>=>{const{data,error}=await supabase.auth.signUp({email:email.trim().toLowerCase(),password,options:{data:{display_name:name.trim()}}});if(error)return{error:authError(error)};return data.session?{error:null}:{error:null,needsEmailConfirmation:true}},[]);
 const signInWithPassword=useCallback(async(email:string,password:string):Promise<AuthResult>=>{const{error}=await supabase.auth.signInWithPassword({email:email.trim().toLowerCase(),password});return{error:error?authError(error):null}},[]);
 const signInWithGoogle=useCallback(async():Promise<AuthResult=>{const{error}=await supabase.auth.signInWithOAuth({provider:"google",options:{redirectTo:`${window.location.origin}/home`,queryParams:{access_type:"offline",prompt:"select_account"}}});return{error:error?authError(error):null}},[]);
 const signOut=useCallback(async()=>{await supabase.auth.signOut()},[]);
 const noop=useCallback(()=>{},[]);
 const ctx=useMemo(()=>({state,hydrated,authLoading,update,signUpWithPassword,signInWithPassword,signInWithGoogle,signOut,awardXp:async()=>null,toggleHabit:noop,addHabit:noop,removeHabit:noop,completeWorkout:noop,toggleExercise:noop}),[state,hydrated,authLoading,update,signUpWithPassword,signInWithPassword,signInWithGoogle,signOut,noop]);
 return <VeyraContext.Provider value={ctx}>{children}</VeyraContext.Provider>
}
export function useVeyra(){const ctx=useContext(VeyraContext);if(!ctx)throw new Error("useVeyra must be used within VeyraProvider");return ctx}
