/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as GameRouteImport } from './routes/game'
import { Route as GroomingRouteImport } from './routes/grooming'
import { Route as HabitsRouteImport } from './routes/habits'
import { Route as HomeRouteImport } from './routes/home'
import { Route as NutritionRouteImport } from './routes/nutrition'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PresentationRouteImport } from './routes/presentation'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as WorkoutRouteImport } from './routes/workout'
import { Route as AcademyIndexRouteImport } from './routes/academy.index'
import { Route as AcademyExerciseIdRouteImport } from './routes/academy.$exerciseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const GroomingRoute = GroomingRouteImport.update({
  id: '/grooming',
  path: '/grooming',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsRoute = HabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRoute = NutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationRoute = PresentationRouteImport.update({
  id: '/presentation',
  path: '/presentation',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutRoute = WorkoutRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyIndexRoute = AcademyIndexRouteImport.update({
  id: '/academy/',
  path: '/academy/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyExerciseIdRoute = AcademyExerciseIdRouteImport.update({
  id: '/academy/$exerciseId',
  path: '/academy/$exerciseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/coach': typeof CoachRoute
  '/game': typeof GameRoute
  '/grooming': typeof GroomingRoute
  '/habits': typeof HabitsRoute
  '/home': typeof HomeRoute
  '/nutrition': typeof NutritionRoute
  '/onboarding': typeof OnboardingRoute
  '/presentation': typeof PresentationRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/workout': typeof WorkoutRoute
  '/academy/$exerciseId': typeof AcademyExerciseIdRoute
  '/academy/': typeof AcademyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/coach': typeof CoachRoute
  '/game': typeof GameRoute
  '/grooming': typeof GroomingRoute
  '/habits': typeof HabitsRoute
  '/home': typeof HomeRoute
  '/nutrition': typeof NutritionRoute
  '/onboarding': typeof OnboardingRoute
  '/presentation': typeof PresentationRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/workout': typeof WorkoutRoute
  '/academy/$exerciseId': typeof AcademyExerciseIdRoute
  '/academy': typeof AcademyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/coach': typeof CoachRoute
  '/game': typeof GameRoute
  '/grooming': typeof GroomingRoute
  '/habits': typeof HabitsRoute
  '/home': typeof HomeRoute
  '/nutrition': typeof NutritionRoute
  '/onboarding': typeof OnboardingRoute
  '/presentation': typeof PresentationRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/workout': typeof WorkoutRoute
  '/academy/$exerciseId': typeof AcademyExerciseIdRoute
  '/academy/': typeof AcademyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/achievements'
    | '/admin'
    | '/auth'
    | '/coach'
    | '/game'
    | '/grooming'
    | '/habits'
    | '/home'
    | '/nutrition'
    | '/onboarding'
    | '/presentation'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/progress'
    | '/workout'
    | '/academy/$exerciseId'
    | '/academy/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/achievements'
    | '/admin'
    | '/auth'
    | '/coach'
    | '/game'
    | '/grooming'
    | '/habits'
    | '/home'
    | '/nutrition'
    | '/onboarding'
    | '/presentation'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/progress'
    | '/workout'
    | '/academy/$exerciseId'
    | '/academy'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/achievements'
    | '/admin'
    | '/auth'
    | '/coach'
    | '/game'
    | '/grooming'
    | '/habits'
    | '/home'
    | '/nutrition'
    | '/onboarding'
    | '/presentation'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/progress'
    | '/workout'
    | '/academy/$exerciseId'
    | '/academy/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AchievementsRoute: typeof AchievementsRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CoachRoute: typeof CoachRoute
  GameRoute: typeof GameRoute
  GroomingRoute: typeof GroomingRoute
  HabitsRoute: typeof HabitsRoute
  HomeRoute: typeof HomeRoute
  NutritionRoute: typeof NutritionRoute
  OnboardingRoute: typeof OnboardingRoute
  PresentationRoute: typeof PresentationRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  WorkoutRoute: typeof WorkoutRoute
  AcademyExerciseIdRoute: typeof AcademyExerciseIdRoute
  AcademyIndexRoute: typeof AcademyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grooming': {
      id: '/grooming'
      path: '/grooming'
      fullPath: '/grooming'
      preLoaderRoute: typeof GroomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits': {
      id: '/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof HabitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition': {
      id: '/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof NutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentation': {
      id: '/presentation'
      path: '/presentation'
      fullPath: '/presentation'
      preLoaderRoute: typeof PresentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout': {
      id: '/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof WorkoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/': {
      id: '/academy/'
      path: '/academy'
      fullPath: '/academy/'
      preLoaderRoute: typeof AcademyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/$exerciseId': {
      id: '/academy/$exerciseId'
      path: '/academy/$exerciseId'
      fullPath: '/academy/$exerciseId'
      preLoaderRoute: typeof AcademyExerciseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AchievementsRoute: AchievementsRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CoachRoute: CoachRoute,
  GameRoute: GameRoute,
  GroomingRoute: GroomingRoute,
  HabitsRoute: HabitsRoute,
  HomeRoute: HomeRoute,
  NutritionRoute: NutritionRoute,
  OnboardingRoute: OnboardingRoute,
  PresentationRoute: PresentationRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  WorkoutRoute: WorkoutRoute,
  AcademyExerciseIdRoute: AcademyExerciseIdRoute,
  AcademyIndexRoute: AcademyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
